set_property PACKAGE_PIN C4 [get_ports uart_in]
set_property IOSTANDARD LVCMOS33 [get_ports uart_in]

set_property PACKAGE_PIN U16 [get_ports indicate_leds[7]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[7]]
set_property PACKAGE_PIN U17 [get_ports indicate_leds[6]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[6]]
set_property PACKAGE_PIN V17 [get_ports indicate_leds[5]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[5]]
set_property PACKAGE_PIN R18 [get_ports indicate_leds[4]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[4]]
set_property PACKAGE_PIN N14 [get_ports indicate_leds[3]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[3]]
set_property PACKAGE_PIN J13 [get_ports indicate_leds[2]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[2]]
set_property PACKAGE_PIN K15 [get_ports indicate_leds[1]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[1]]
set_property PACKAGE_PIN H17 [get_ports indicate_leds[0]]
set_property IOSTANDARD LVCMOS33 [get_ports indicate_leds[0]]

 set_property PACKAGE_PIN V11 [get_ports status_leds[7]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[7]]
set_property PACKAGE_PIN V12 [get_ports status_leds[6]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[6]]
set_property PACKAGE_PIN V14 [get_ports status_leds[5]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[5]]
set_property PACKAGE_PIN V15 [get_ports status_leds[4]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[4]]
set_property PACKAGE_PIN T16 [get_ports status_leds[3]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[3]]
set_property PACKAGE_PIN U14 [get_ports status_leds[2]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[2]]
set_property PACKAGE_PIN T15 [get_ports status_leds[1]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[1]]
set_property PACKAGE_PIN V16 [get_ports status_leds[0]]
set_property IOSTANDARD LVCMOS33 [get_ports status_leds[0]]


set_property package_pin E3 [get_ports ssd_clk]
set_property iostandard LVCMOS33 [get_ports ssd_clk]


set_property package_pin J14 [get_ports Anode[3]]
set_property iostandard LVCMOS33 [get_ports Anode[3]]
set_property package_pin T9 [get_ports Anode[2]]
set_property iostandard LVCMOS33 [get_ports Anode[2]]
set_property package_pin J18 [get_ports Anode[1]]
set_property iostandard LVCMOS33 [get_ports Anode[1]]
set_property package_pin J17 [get_ports Anode[0]]
set_property iostandard LVCMOS33 [get_ports Anode[0]]

set_property package_pin T10 [get_ports SSD_out[6]]
set_property iostandard LVCMOS33 [get_ports SSD_out[6]]
set_property package_pin R10 [get_ports SSD_out[5]]
set_property iostandard LVCMOS33 [get_ports SSD_out[5]]
set_property package_pin K16 [get_ports SSD_out[4]]
set_property iostandard LVCMOS33 [get_ports SSD_out[4]]
set_property package_pin K13 [get_ports SSD_out[3]]
set_property iostandard LVCMOS33 [get_ports SSD_out[3]]
set_property package_pin P15 [get_ports SSD_out[2]]
set_property iostandard LVCMOS33 [get_ports SSD_out[2]]
set_property package_pin T11 [get_ports SSD_out[1]]
set_property iostandard LVCMOS33 [get_ports SSD_out[1]]
set_property package_pin L18 [get_ports SSD_out[0]]
set_property iostandard LVCMOS33 [get_ports SSD_out[0]]



